services:
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  bayeta_app:
    build: .
    container_name: bayeta_app
    depends_on:
      - mongo_db
    ports:
      - "5000:5000"
    command: python app.py

volumes:
  mongo-data:
